batch_size:
  desc: ''
  sort: 2
  value: 32
epochs:
  desc: ''
  sort: 1
  value: 50
learning_rate:
  desc: ''
  sort: 0
  value: 0.004
lookback:
  desc: ''
  sort: 3
  value: 60
optimizer:
  desc: ''
  sort: 6
  value: AdamW
save_path:
  desc: ''
  sort: 5
  value: ./checkpoint/2024-11-13 18:10:09.114407
trainset_ratio:
  desc: ''
  sort: 4
  value: 0.95
