# Generated by Django 3.2.25 on 2024-09-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255, verbose_name='游戏名称')),
                ('release_date', models.CharField(max_length=255, verbose_name='发布日期')),
                ('cur_price', models.CharField(max_length=255, verbose_name='当前价格')),
                ('last_price', models.CharField(max_length=255, verbose_name='上次价格')),
                ('tags', models.TextField(blank=True, null=True, verbose_name='标签')),
                ('steam_db_rating', models.CharField(max_length=255, verbose_name='SteamDB 评分')),
                ('good_reviews_count', models.IntegerField(blank=True, null=True, verbose_name='好评数量')),
                ('negative_reviews_count', models.IntegerField(blank=True, null=True, verbose_name='差评数量')),
                ('all_time_peak', models.IntegerField(blank=True, null=True, verbose_name='历史峰值')),
                ('page_url', models.URLField(blank=True, max_length=255, null=True, verbose_name='页面链接')),
            ],
        ),
    ]
