# Generated by Django 3.2.25 on 2024-09-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1星'), (2, '2星'), (3, '3星'), (4, '4星'), (5, '5星')], verbose_name='评分')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.game', verbose_name='游戏')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.customuser', verbose_name='用户')),
            ],
        ),
    ]
