# Generated by Django 3.2.25 on 2024-09-30 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_gamerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='评分时间'),
        ),
    ]
